version: '3.4'



services:
    nginx-release:
        image: nginx
        ports:
          - 80:8114
          #- 8191:8191
        volumes:
          - ./build:/usr/share/nginx/html
          - ../iot-admin/build:/usr/share/nginx/html2
          - /root/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
          
          - /root/nginx/logs:/var/log/nginx
        environment:
          #- TZ=Asia/Shanghai
          #- COLLECTOR_PORT=8191

          #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
          
          - ENV=production
          - REACT_APP_API_HOST=http://testenergyapi.wznhjc.cn

    # db:

    #    image: mysql:5.7

    #    restart: always

    #   #command: --init-file /db/init.sql --character-set-server=utf8mb4 --explicit_defaults_for_timestamp --sql-mode=""

    #    environment:

    #      - MYSQL_ROOT_PASSWORD=pqWMzCi4raKtbtnwRvU9o

    #      - TZ=Asia/Shanghai

    #    ports:

    #      - 3306:3306

    #    volumes:

    #      - ./db:/db

    #      - ./db/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro

#    mongo:
#
#      image: mongo:latest
#
#      #command: mongod --smallfiles
#
#      ports:
#
#        - 27017:27017
#
#      depends_on:
#
#        - mongo_seed
#
#
#
#    mongo_seed:
#
#      build:
#
#        context: ops
#
#        dockerfile: mongo/Dockerfile_mongo_seed
#
#      entrypoint: /wait-for-it.sh mongo:27017 --
#
#      command: mongoimport --host mongo --db local --collection projects --type json --file /init.json

    redis:

      image: redis:4

      restart: always

      ports:

        - 6379:6379


    energy-api:

        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/energy-api:v1

        ports:

          - 8081:8080

        volumes:

          - ".:/src"

          - /src/node_modules/

        environment:

          - TZ=Asia/Shanghai

          #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]

          #- RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}

          - RDS_READ=[{"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}]

          - RDS_WRITE={"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}


          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737

          - MONGODB_URL=mongodb://47.111.155.7:27017/energy
          - REDIS_URL=redis://redis:6379

        depends_on:

          #- db

          #- mongo

          - redis

    collector-release:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/collector:v1
        ports:
          #- 9010:9010
          - 8191:8191
        environment:
          - TZ=Asia/Shanghai
          - COLLECTOR_PORT=8191

          #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
          #- RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}
          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737
          - RDS_READ=[{"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}]
          - RDS_WRITE={"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}

          - MONGODB_URL=mongodb://47.111.155.7:27017/energy

          - MQ_HOST=redis
          - MQ_PORT=6379
          - HTTP_PORT=9091
          - MQ_PASS=
          - SHOW_LOG=true
          - ENV=production

    api-release:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/api:v1
        ports:
          - 8085:8085
        environment:
          - TZ=Asia/Shanghai
#          - RDS_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}]
#          - RDS_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}
#          - MONGODB_URL=mongodb://mongo:27017/EnergyManage
#
          #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
          #- RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}
          - RDS_READ=[{"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}]
          - RDS_WRITE={"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}

          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737

          - MONGODB_URL=mongodb://47.111.155.7:27017/energy

          - DEVELOPMENT=true
          - ENV=prodution
          - MQ_HOST=redis
          - MQ_PORT=6379
          - MQ_PASS=
          - APP_SERVICE=
          - RPC_MESSAGE=
          - RPC_ELEPHANTRY=
          - RPC_FINANCE=
          - RPC_PACKAGE=
        depends_on:
          #- db
          - redis
          #- mongo

    clupus-release:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/clupus:v1
        ports:
          - 8299:8299
          - 58299:58299
        environment:
          - TZ=Asia/Shanghai

#          - RDS_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}]
#          - RDS_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}
#          - MONGODB_URL=mongodb://mongo:27017/EnergyManage
#
          #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
          #- RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}
          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737

          - RDS_READ=[{"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}]
          - RDS_WRITE={"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}
          - MONGODB_URL=mongodb://47.111.155.7:27017/energiy

          - MQ_HOST=redis
          - MQ_PORT=6379
          - RPC_IP=0.0.0.0
          - MQ_PASS=
          - ENV=production
          - APP_ID=EMe374f490bdc411e4864359c68eeb10e7
          - APP_SECRET=c4b7a590ef859f8443cd631375dc0485
          - API_HOST=api
        depends_on:
          #- db
          - redis
          #- mongo
          #
    falcon-release:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/falcon:v1
        ports:
          - 8333:8333
        environment:
          - TZ=Asia/Shanghai

#          - RDS_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}]
#          - RDS_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}
#          - MONGODB_URL=mongodb://mongo:27017/EnergyManage
#
           
          - RDS_READ=[{"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}]
          - RDS_WRITE={"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}

          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737

          - MONGODB_URL=mongodb://47.111.155.7:27017/energy
          #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
          #- RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}
          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737

          - RPC_IP=0.0.0.0
        #depends_on:
          #- db
          #- mongo
    columba-release:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/columba:v1
        environment:
          - TZ=Asia/Shanghai

            #- RDS_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}]
            #- RDS_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}
            #- MONGODB_URL=mongodb://mongo:27017/EnergyManage

            #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
            #- RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}
            #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737
    
          - RDS_READ=[{"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}]
          - RDS_WRITE={"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}
          - MONGODB_URL=mongodb://47.111.155.7:27017/energy
          - MQ_HOST=redis
          - MQ_PORT=6379
          - MQ_PASS=
          - ENV=production
          - SHOW_LOG=true
          - RPC_FINANCE_IP=127.0.0.1
        depends_on:
            #- db
          - redis
            #- mongo


    beetle-release:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/beetle:v1
        environment:
          - TZ=Asia/Shanghai

          #- RDS_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}]
          #- RDS_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}
          #- MONGODB_URL=mongodb://mongo:27017/EnergyManage

          #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
          #- RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}
          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737

          - RDS_READ=[{"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}]
          - RDS_WRITE={"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}

          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737

          - MONGODB_URL=mongodb://47.111.155.7:27017/energy
          - MQ_HOST=redis
          - MQ_PORT=6379
          - MQ_PASS=
          - ENV=production
        depends_on:
          #- db
          - redis
          #- mongo
         
    guardian-release:
        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/guardian:v1
        environment:
          - TZ=Asia/Shanghai

          #- RDS_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}]
          #- RDS_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}
          #- MONGODB_URL=mongodb://mongo:27017/EnergyManage

          #- RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
          #- RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}
          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737

          #- RDS_READ=[{"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}]
          #- RDS_WRITE={"host":"47.111.155.7","port":3306,"username":"root","password":"Jzjn2019","database":"energy"}
                
          #- MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737
          - DB_HOST=47.111.155.7
          - DB_NAME=energy
          - DB_USER=root
          - DB_PASSWORD=Jzjn2019
          - MONGODB_URL=mongodb://47.111.155.7:27017/energy
          - MQ_HOST=redis
          - MQ_PORT=6379
          
          - ENERGY_API_PORT_8080_TCP_PROTO=tcp
          - CLUPUS_SERVICE_PORT_HTTP=8919
          - CLUPUS_PORT_8919_TCP_ADDR=47.111.155.7
          - API_PORT_8085_TCP=tcp://47.111.155.7:8085
          - ENERGY_API_SERVICE_HOST=47.111.155.7
          - CLUPUS_SERVICE_HOST=47.111.155.7
          - CLUPUS_PORT_8919_TCP_PROTO=tcp
          - CLUPUS_PORT_58299_TCP=tcp://47.111.155.7:58299
          - API_SERVICE_HOST=47.111.155.7
          - CLUPUS_PORT_8919_TCP=tcp://47.111.155.7:8919
          - CLUPUS_PORT_58299_TCP_PROTO=tcp
          - CLUPUS_PORT_58299_TCP_ADDR=47.111.155.7
          - API_PORT_8085_TCP_ADDR=47.111.155.7
          - ENERGY_API_PORT=tcp://47.111.155.7:8080
          - CLUPUS_SERVICE_PORT=8919
          - CLUPUS_SERVICE_PORT_GRPC=58299
          - CLUPUS_PORT_58299_TCP_PORT=58299
          - API_PORT_8085_TCP_PROTO=tcp
          #- KUBERNETES_SERVICE_HOST=172.21.0.1
          - ENERGY_API_SERVICE_PORT=8080
          - KUBERNETES_PORT_443_TCP_PROTO=tcp
          - ENERGY_API_PORT_8080_TCP_PORT=8080
          - API_SERVICE_PORT=8085
          - API_PORT_8085_TCP_PORT=8085
          #- KUBERNETES_PORT_443_TCP=tcp://172.21.0.1:443
          #- KUBERNETES_PORT=tcp://172.21.0.1:443
          - ENERGY_API_PORT_8080_TCP_ADDR=47.111.155.7
          - CLUPUS_PORT=tcp://47.111.155.7:8919
          - CLUPUS_PORT_8919_TCP_PORT=8919
          - API_PORT=tcp://47.111.155.7:8085
          #- KUBERNETES_SERVICE_PORT=443
          - ENERGY_API_PORT_8080_TCP=tcp://47.111.155.7:8080
          - NODE_VERSION=10.16.0
          - YARN_VERSION=1.16.0
          - NPM_CONFIG_LOGLEVEL=info
          - HOME=/root
          - ENV=production
        depends_on:
          #- db
          - redis
          #- mongo
#
#
#
#
##    beetle-release:
##    #        image: registry-vpc.cn-hangzhou.aliyuncs.com/jzjn-mirror-test/beetle:v1
##    #        environment:
##    #          - TZ=Asia/Shanghai
##    #
##    #          #- RDS_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}]
##    #          #- RDS_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"energymanage"}
##    #          #- MONGODB_URL=mongodb://mongo:27017/EnergyManage
##    #
##    #          - RDS_READ=[{"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}]
##    #          - RDS_WRITE={"host":"rm-bp1ei3p867z9m8gltio.mysql.rds.aliyuncs.com","port":3306,"username":"energy","password":"pqWMzCi4raKtbtnwRvU9o","database":"energy"}
#    #          - MONGODB_URL=mongodb://energy:ttULeRa2RdbcouHFkkZje@dds-bp1beaec5447bf641.mongodb.rds.aliyuncs.com:3717,dds-bp1beaec5447bf642.mongodb.rds.aliyuncs.com:3717/energy?replicaSet=mgset-15906737
#    #
#    #          - MQ_HOST=redis
#    #          - MQ_PORT=6379
#    #          - MQ_PASS=
#    #          - ENV=production
#    #        depends_on:
#    #          #- db
#    #          - redis
#    






